status = [
  'linter-check',
  'playground-build (Node.js 10)',
  'playground-build (Node.js 12)',
  'playground-build (Node.js 14)',
  'style-check (Node.js 10)',
  'style-check (Node.js 12)',
  'style-check (Node.js 14)'
]
# 1 hour timeout
timeout-sec = 3600
